name:                polysemy-arrows
version:             0.1.0.0
github:              "rpeszek/experiments/polysemy-arrows"
license:             BSD3
author:              "Robert Peszek"
maintainer:          "example@example.com"
copyright:           "2021 Robert Peszek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/polysemy-arrows#readme>

dependencies:
- base >= 4.7 && < 5
- polysemy
- polysemy-plugin

library:
  source-dirs: src

tests:
  polysemy-arrows-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polysemy-arrows

ghc-options:
  - -O2 -flate-specialise -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin
  - -fwarn-incomplete-patterns
  - -fwarn-unused-imports
  - -Wno-partial-type-signatures

default-extensions:
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies  