name:                alternative
version:             0.1.0.0
github:              "githubuser/alternative"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/alternative#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- mtl
- containers
- attoparsec
- transformers
- mtl
- trifecta
- megaparsec

library:
  source-dirs: src
  ghc-options:
  - -fwarn-unused-imports
  - -fwarn-incomplete-patterns
  - -Wno-partial-type-signatures

tests:
  alternative-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alternative
    - doctest
    - doctest-discover
